# Generated by Django 4.1.4 on 2022-12-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstats',
            name='amount',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
