# Generated by Django 4.1.4 on 2023-01-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_eventstats_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='w', max_length=1),
        ),
    ]
